# -*- mode: ruby -*-end
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # Hyper-V Provider Specific Configuration
  config.vm.provider "hyperv" do |h|
    h.enable_virtualization_extensions = true
    h.linked_clone = true
    h.memory = 2048
    h.maxmemory = 2048
  end

  # Virtualbox Provider Specific Configuration
  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
    v.cpus = 2
  end

  # VMware Workstation Provider Specific Configuration
  config.vm.provider "vmware_desktop" do |v|
    v.vmx["memsize"] = 2048
    v.vmx["numvcpus"] = 2
  end

  config.vm.define "rocky9" do |rocky9|
    # VM Shared Configuration
    rocky9.vm.box = "generic/rocky9"
    rocky9.vm.hostname = "rocky9"

    # Hyper-V VM Specific Configuration
    rocky9.vm.provider 'hyperv' do |h, override|
      override.vm.synced_folder ".", "/vagrant", type: "rsync"
      override.vm.network "public_network", bridge: "Default Switch"
    end

    # Virtualbox VM Specific Configuration
    rocky9.vm.provider 'virtualbox' do |v, override|
      override.vm.synced_folder ".", "/vagrant"
    end

    # VMware Workstation VM Specific Configuration
    rocky9.vm.provider 'vmware_desktop' do |v, override|
      override.vm.synced_folder ".", "/vagrant"
    end
  end

  # VM Shared Provisioning Placeholder
  config.vm.provision "shell", inline: <<-SHELL
    #!/bin/bash

    # Upgrade all packages except kernel
    sudo dnf upgrade -y --exclude=kernel*

    # Install container-tools meta package
    sudo dnf install -y container-tools

    # Verify that podman is working
    podman run --rm --rmi docker.io/library/hello-world
  SHELL
end
