---
- name: Deploy Cockpit
  hosts: all

  tasks:
    - name: Update package cache
      apt:
        update_cache: yes

    - name: Install Cockpit package
      apt:
        name: cockpit
        state: present

    - name: Start Cockpit service
      systemd:
        name: cockpit
        state: started
        enabled: yes